### ISSUE TITLE
consider mapping out the site's architecture in an easily accessable document or format

### ISSUE THREAD

**Issue by 31547** [BlocklandGlass/GlassWebsite#37]
this is just to make working on the site simpler.
new contributors may not actually know what is what, so adding intended endpoints or places of interest somewhere like a README would help with that.  also, it might help with giving the project more dierction.

**Comment by dpendic** [comment]
phpdocs are now at https://blocklandglass.com/sitedocs

**Comment by McTwist** [comment]
How often will these documentation be updated? I'd like to add some to the classes I manage.

**Comment by dpendic** [comment]
@McTwist They're updated manually right now, phpdocumentor (phpdoc?) can be installed using composer and the make_docs.sh script should do the rest. I want to make this run on the server whenever a commit is made so that we don't have to track it all through git, but haven't gotten around to it.

If you're on Windows, I haven't actually tested the bat file yet and the parameters aren't the same. If you commit documented classes and haven't generated the docs, I'll do so.

**Comment by McTwist** [comment]
Cool. I'll see to allocate time to make it possible. I may even try that batch script if I need to check how it looks like.
